#!/bin/bash

echo "Installing dependencies ...."
sudo apt-get install libxrender1 libxrender1:i386 \
                     libxcb-render0 libxcb-render0:i386 \
					 libxcb-render-util0 libxcb-render-util0:i386 \
					 libxcb-shape0 libxcb-shape0:i386 \
					 libxcb-randr0 libxcb-randr0:i386 \
					 libxcb-xfixes0 libxcb-xfixes0:i386 \
					 libxcb-sync0 libxcb-sync0:i386 \
					 libxcb-shm0 libxcb-shm0:i386 \
					 libxcb-icccm4 libxcb-icccm4:i386 \
					 libxcb-keysyms1 libxcb-keysyms1:i386 \
					 libxcb-image0 libxcb-image0:i386 \
					 libfontconfig1 libfontconfig1:i386 \
					 libfreetype6 libfreetype6:i386 \
					 libXi6 libXi6:i386 \
					 libxext6 libxext6:i386 \
					 libx11-6 libx11-6:i386 \
					 libxcb1 libxcb1:i386 \
					 libX11-xcb1 libX11-xcb1:i386 \
					 libsm6 libsm6:i386 \
					 libice6 libice6:i386 \
					 libglib2.0-0 libglib2.0-0:i386 \
					 libpthread-stubs0 libpthread-stubs0:i386 \
					 libstdc++6:i386 \
					 libpng12-0:i386 \
					 libxrandr2:i386 \
					 libpulse0:i386
